const text = `
Le verre entre nous s’embue de l’haleine du renard. Je suis assis dans la vitrine et j’inspire. Seul. Je suis une œuvre de l’exposition, quelque chose entre l’œuf d’autruche, le squelette de chauve-souris et la question même de savoir comment je m’intègre dans cet ordre. Le renard me regarde, à travers ses prunelles devenues laiteuses. Je fais le mort, les yeux ouverts. Le renard ne dit rien. Je sursaute légèrement, et la vitrine aussi.  

Le nom des cochons sauvages, ici, est de sang. L’un d’entre eux se tient inerte au commencement d’un mur couvert de graffitis, le trou d’insertion raccommodé, les coutures bien serrées. Il se fait tard, les invités sont dans le hall, avec leurs boissons, conversant entre pairs. Je serpente entre les gens en direction des salles d’exposition. C’est calme, les visiteurs parlent à voix basse, comme s’ils ne voulaient pas effrayer les animaux. Le parquet grince et s’accorde à l’odeur légèrement moisie. Aucun bruit, aucun mouvement abrupt ne pourrait ici effrayer les bêtes, elles sont silencieuses, comme si elles attendaient désirant le coup de fusil. Comme si Meduse n’avait pas été décapitée, mais qu’elle avait fuit dans la forêt et que quelqu’un avait ramené tous les animaux ici, arrangés et installés en vitrine, flanqués d’explications, de détails exhaustifs, taxinomiques. Tout l’animal changé en texte pour ne jamais mourir. J’essaie de me tenir droit, mais ma posture corporelle dépasse de façon disgracieuse de la masse, ce qui est remarqué par les autres, je sens leur regard sur ma peau. Je me concentre sur le cartel en face de moi, et j’essaie de me souvenir à quoi ressemble le fait de lire. Les hommes portent des costumes, les femmes des tailleurs ou des robes, elles se sont entouré la gorge d’un foulard, parfumées, elles ont des varices sur les mollets. Ma robe est mûre, il conviendrait de s’en défaire. Ils s’attendent à ce que je regarde les animaux, les morts, qui eux ne regardent personne, dont les yeux artificiels s’extirpent de la salle. J’ose à peine regarder dans ces yeux, et lorsque mon regard passe malgré tout sur eux, je tâche de ne pas m’y suspendre. Comme s’il s’agissait de lettres étrangères, que je ne peux reconnaître comme une langue. Non pas fenêtres sur l’âme, mais sur les nuages, du plâtre ou du polyuréthane.  

Le renard connaît ma peur. Il m’a connu au tout début, avant que j’aie peur. Mon père m’avait dit que le renard était déjà là à ma naissance et qu’il me survivrait longtemps. Au départ le renard s’immisça dans les histoires, mon père ne le remarqua peut-être pas du tout, mais moi oui. Avant même que je puisse parler, avant même que je puisse poser des questions sur le renard, je remarquais comment le renard m’entrevoyait de depuis les histoires, et voyait comment j’observais fasciné les lèvres de mon père. Lorsque j’appris à parler, j’ai posé la question du renard. Ainsi il vint encore plus souvent dans les histoires, comme si par mes mots il s’était multiplié. J’avouai ma peur à mon père dès que je trouvais le mot pour, et il me dit en riant qu’elle était sans fondement. Et il me raconta encore une histoire de renard, et j’y trouvais de nouvelles raisons d’avoir peur. Non pas que j’aie eu besoin de raisons, mon corps connaissait le danger qui venait du dehors, de l’obscurité que je voyais la nuit devant ma fenêtre et dans laquelle tous les animaux se dissimulaient, invisibles comme dans les histoires. Mais qui n’y resteraient pas. Mon père me dit que si je voyais le renard, je ne devais pas lui montrer ma peur. Je lui demandai à quoi ressemblait ma peur, car elle n’avait, comme le renard, pas de visage. Mon père me dit qu’on pouvait la sentir, lorsque je commençais à transpirer, l’entendre lorsque ma respiration s’accélérait, la voir lorsque je commençais à trembler. Alors j’interdis à mon corps de montrer ses signes, et je retins ma peur autant que possible cachée en moi. Si on ouvrait mon corps, peut-être pourrait-on l’y retrouver.  

Désormais le renard est éclot des histoires. Il est assis devant la vitrine, son visage proche du mien, une simple vitre nous sépare l’un de l’autre. Peut-être que le renard a une nouvelle pour moi. Ou moi pour lui, je n’en sais rien. Le renard ne demande pas l’autorisation avant de se servir, le verre ne le retiendra pas. Le renard regarde dans la vitrine et rend le regard depuis elle. Entre nos yeux s’étend un abîme d’incompréhension.  

Les autres invités sont mécontents que je sois des leurs, une catin, un clochard chez les bourgeois, je ne pourrais que trop en jouir. Quelqu’un m’effleure, je m’excuse. L’autre ne répond rien. Au plafond, des oiseaux gelés en plein vol, leurs ailes ne battent pas, mais des fils de nylon les tiennent dans les airs. Je regarde vers le haut, puis mes pieds, puis je remarque un homme. Je lisse ma robe qui accroche mes collants, je cherche un miroir, mais je ne trouve que l’homme. Je ne sais depuis combien de temps il est là. Ses cheveux sont noirs mêlés de gris, les premiers boutons de sa chemise sont ouverts. Il fronce les sourcils. La chemise est blanche comme si elle venait d’être blanchie, les dents aussi. Je continue, j’entre dans un couloir de trophées aux murs pleins de cornes. L’homme se tient dans un coin obscur. Il boit du champagne dans un verre en forme de tulipe, l’emporte avec lui dans chaque pièce, le tient par la tige près de son ventre. Mes yeux sont très proches de mes tempes, mais je ne peux regarder derrière moi, je m’attrape la nuque. Mon corps sait que l’homme me suit, je sens ma sueur. Je passe par une galerie d’armes innombrables, je grimpe l’escalier en vitesse, la balustrade en ivoire est sculptée de plumes. On se retourne agacé sur mon passage. L’homme est là. Je ne sais pas si il n’y en a qu’un, ou si il y en a plusieurs identiques. Ma robe se démet de manière incontrôlable et se serre, se retroussant sur les bords. Je m’avance la main dans les cheveux, je m’en arrache presque. L’homme sirote son verre.  

Dans une autre enfance je le jouais, le renard, comme rôle de théâtre. Je n’ai aucune idée de la manière dont ce rôle m’est tombé dessus, peut-être que mon maître voulait que je surmonte ma peur. Avant de jouer cette pièce, il nous emmena au zoo, afin que nous y voyions les vrais animaux et que nous puissions étudier leur comportement afin de les reproduire de façon authentique sur scène. Aucune sortie ne me faisait plus peur que celle-ci, tandis que les autres enfants ne pouvaient attendre de voir leurs modèles animaux en vrai. Et tous, ils étaient déçus de voir les animaux allongés lourdement dans leurs cages, tournant en rond, sans réaction à leurs appels. Je pris du recul et regardais lentement le renard en lequel je devais me changer. Le regard ne m’accorda aucun regard. L’image que j’avais de ces animaux nous tombant dessus en rampant et en volant correspondait tout aussi peu à celle qu’en avaient les autres enfants, comme des figures chantantes et dansantes de dessins animés. Mais ils étaient enfermés ici dans leurs cages de la même façon qu’ils l’avaient été dans les histoires de mon père, à la nature desquelles je ne croyais pas. Il me paraissait trop dangereux et trop probable, que les mots se fissent vérités, et trop improbable qu’ici derrière des cages gise la vérité. J’étais persuadé qu’ils me trouveraient au moment où je m’y attendrais le moins, aucune image ne me préparerait à ce ça représentait.  

Lorsque, après des mois de répétitions, nous jouâmes notre pièce, je pensai au renard dans sa cage qui ne m’avait pas perçu. Je me tins sur la scène et je l’imitai, je me suis mis à regarder devant moi, je ne réagis pas aux autres qui jouaient leur rôle sagement déguisés, alors que j’attendais ma pâtée. Sans mot. Le renard ne parlait pas, lui non plus, si j’avais commencé, cela aurait gâché l’illusion. A l’entracte, dès le tomber du rideau, je me ruai dans les loges et j’aperçus mon visage cuivré dans le miroir. Le maître entra, m’adressa la parole, je l’écoutai mais ne compris rien. Lorsque la deuxième partie commença, j’avais fui, mon costume suspendu à la chaise, essuyé frénétiquement et humide. Pour le reste du spectacle, le maître finit par lire le texte depuis le premier rang et les autres animaux discutèrent avec un renard invisible. Je revins seulement après l’extinction des projecteurs, mais il faisait sombre et personne ne me vit. Mon maître ne me fit aucun reproche, pas même lorsque peu de temps après il perdit son emploi. Il me fit ses adieux et me dit que je n’avais pas à avoir peur. Du renard, je pense. A l’époque, j’avais presque perdu ma peur. Mais tout le monde parlait d’à quel point il avait été un mauvais enseignant. Comme s’il avait fait danser les enfants, comme si ils les avait pris en chasse. C’est que nous étions des animaux.  

Si au moins on pouvait mal se comprendre, mais le renard ne peut pas parler. On ne le lui a pas appris, peut-être parce qu’il ne peut pas l’apprendre. De toute façon, c’est maintenant trop tard, aucun mot ne fera le pont de lui à moi, le verre de la vitrine est bien en place et rend plus difficile de voir. Quelque part une porte se ferme. Le renard regarde autour de lui, et à nouveau vers moi. Son museau touche le verre. Et la lumière s’éteint.  

Dans un couloir étroit je me tiens devant une image qui représente une chasse à l’éléphant. L’éléphant me regarde avec de grands yeux, sa bouche est déchirée et sa trompe relevée, sa queue s’agitant une dernière fois dans les airs. Les chasseurs regardent les coups de feu de dos, je ne trouve pas la balle, pas plus que le trou d’insertion. On l’a abattu avec grandes précautions, bientôt son corps s’effondrera et on l’enlèvera pour l’emmener à la maison. L’homme me regarde chercher la cartouche. Puis il se place devant une image accrochée au mur d’en face, son dos proche du mien. Il commence à parler, pas à l’image, mais à moi. Je me retourne le premier, en commentant ironiquement mon déplacement en cet endroit. Je me gratte la clavicule, je serre mes bras contre mon torse. En se retournant il me jauge de haut en bas. Puis il me tend la main. Il rit, se présente, sort une carte de visite de la poche intérieure de sa veste et me la tend. Je regarde le papier, seuls quelques mots y sont inscrits, son nom, il est avocat et courtier en art. Il me parle d’un vernissage qu’il organise, où il y aurait un meilleur champagne qu’ici. Je devrais venir à ce vernissage, on n’y trouverait pas d’animaux empaillés comme ici, plaisante-t-il. Je me force à sourire et je regarde ses poils de torse où brille une chaîne argentée. Il me demande si je suis seul ici, j’acquiesce. Il n’y a que nous deux dans le couloir, il saisit mon épaule. Il me demande où j’habite et comment je vais faire pour rentrer chez moi, ce n’est pas loin, je vais prendre le dernier métro, je lui réponds. Il propose de me raccompagner à la maison, il est venu avec sa moto, je ne comprend pas l’intérêt de posséder une telle chose dans une grande ville. Je lui demande ce qu’il sait du traitement des animaux. Si il est chasseur ? Il acquiesce. Il me raconte les détails. Derrière nous, le musée ferme ses portes.  

Au moment où il commence à me doigter, je pense à la taxidermie. Les renards sont suspendus la tête à l’envers à un jeune arbre, aux branches basses et à la ramure forte. Comme des fruits murs, ils sont suspendus là, fendus, comme pour être bientôt pelés en plaçant la lame du couteau sur les pattes arrières. L’homme me demande quelque chose, et je fais un bruit qui j’espère suffira de réponse. Je sens la sueur entre nos corps. Du sang goutte des renards morts. Non de l’incision, mais du trou d’insertion, le couteau – il doit être aiguisé mais sans pénétrer jusqu’aux entrailles – glisse entre la peau et le muscle, là où le gras s’accumule. Je me demande combien de temps cela durera, et si il sera déçu. Mon corps se tient là, rien ne s’y cache. La queue est retirée et incisée tout du long, une coupure qui plus tard disparaîtra sous la fourrure touffue. Dans la chambre, c’est calme, seuls les corps font des bruits inévitables. Je m’agrippe à l’extrémité du matelas, il défait mes attaches. Une incision supplémentaire partant de l’anus descend le long du ventre, puis une horizontale, entre les deux pattes avant. On libère les pattes en coupant les tendons de la plante des pieds, afin de pouvoir retirer la peau à partir du haut jusqu’à ce qu’elle pende de la tête du renard comme un manteau humide. Les pates arrières sont tendues roses dans l’air, la queue nue et coudée. Je fourre mon visage dans le coussin et j’essaie de retirer mes collants avec mes orteils, qui n’arrivent qu’à ma cheville. Il devient sauvage, j’essaie d’avoir l’air sauvage, mon corps ne veut pas. Des sons s’échappent de sa bouche, il parle avec mon corps, pas avec moi, ma langue est apprivoisée, elle n’obéit pas. Le conduit auditif est sectionné. Il respire dans mes cheveux, les attrape, je plisse les yeux. Avec le couteau, on va jusqu’aux paupières, la chair y est plus tendre. On met l’index dans l’ouverture par laquelle l’animal regardait alors. Je mords l’oreiller, son corps contracté. Enfin, on coupe les lèvres de la bouche. Tous les liens sont coupés. Les noyaux souriants pendent aux arbres, sans fruit pour les cacher. Au sol la dépouille fume comme des habits humides.  

Lorsque nos corps ont fini, sont devenus animaux, sont mort et nés à nouveau, lorsqu’ils se sont sauvagement entendus et qu’ils étaient incompréhensibles, nous sommes allongés immobiles. Je n’ai plus peur de lui, nous sommes ensembles dans la vitrine, là, pour toujours. Il ne me tombera pas dessus une deuxième fois, il n’y a plus rien à obtenir de moi. Plus tard je me réveille, j’entends sa respiration près de moi, cela pourrait être la respiration de n’importe qui. Quelque part dans la pièce, au pied du lit peut-être, le renard guette dans le noir et me considère. Je vais dans la salle de bain, mon corps s’y tient stérile. Je me regarde dans le miroir, sans me mouvoir. Personne ne me fixe en retour. Dehors, c’est bientôt l’aube. Un renard s’enfuit dans le bois, dans la nature sauvage, il en a vu assez.  

`
function getArrayofSlices (text, parts) {
    moduloText = text.length%parts
    cards = (text.length-moduloText)/parts
    start = 0
    slices = []
    for (i = 0; i < parts; i++) {
        end = start + cards;
        slices.push([start, end]);
        start = end
    }
    slices.push([start+1,start+1+moduloText])    
    return(slices)
}

let slicesChoice = document.querySelector('#fuchsStuecke').value;
let slicesIndex = getArrayofSlices(text, slicesChoice); // Appeler la fonction pour initialiser slicesIndex
let counter = 0;

// Écouteur d'événement pour mettre à jour slicesChoice et slicesIndex lors de l'entrée
document.querySelector('#fuchsStuecke').addEventListener('input', function () {
    slicesChoice = document.querySelector('#fuchsStuecke').value; // Mettre à jour la variable globale
    document.querySelector('#stuecke').textContent = slicesChoice;
    // Met à jour slicesIndex à chaque changement de valeur
    slicesIndex = getArrayofSlices(text, slicesChoice);
});

function getNewSlice(slices, text) {
    if (counter < slicesIndex.length) {
        let textNode = document.createTextNode(text.substring(slices[counter][0],slices[counter][1]))
        let oldDiv = document.querySelector('#textSlice');
        oldDiv.textContent = ""; // Clear old content
        const ulElement = document.querySelector('ul');
        if (ulElement) {
            ulElement.parentNode.removeChild(ulElement);
        }
        oldDiv.appendChild(textNode); // Append the new text node
        counter ++
    } else {counter = 0}
}

document.querySelector("#imgContainer").addEventListener('click', function () {
    getNewSlice(slicesIndex,text)
    if (counter != 0) {
        document.querySelector("#imgContainer").style.width = 11 + counter + "rem";
        document.querySelector("#imgContainer").style.height = 11 + counter + "rem";
        document.querySelector("#imgContainer").style.opacity = 1 - (counter/slicesIndex.length)    }
    })
